apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcx-client-demo-dns-deployment
spec:
  selector:
    matchLabels:
      app: rpcx-client-demo-dns
  replicas: 1
  template:
    metadata:
      labels:
        app: rpcx-client-demo-dns
    spec:
      containers:
      - name: rpcx-client-demo-dns
        image: smallnest/rpcx-client-demo-dns:v0.1.0