apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcx-client-demo3-deployment
spec:
  selector:
    matchLabels:
      app: rpcx-client-demo3
  replicas: 1
  template:
    metadata:
      labels:
        app: rpcx-client-demo3
    spec:
      containers:
      - name: rpcx-client-demo3
        image: smallnest/rpcx-client-demo3:v1.0.1