apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcx-client-demo-api-deployment
spec:
  selector:
    matchLabels:
      app: rpcx-client-demo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: rpcx-client-demo-api
    spec:
      containers:
      - name: rpcx-client-demo-api
        image: smallnest/rpcx-client-demo-api:0.1.0