apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcx-server-demo-nacos-deployment
spec:
  selector:
    matchLabels:
      app: rpcx-server-demo-nacos
  replicas: 3
  template:
    metadata:
      labels:
        app: rpcx-server-demo-nacos
    spec:
      containers:
      - name: rpcx-server-demo-nacos
        image: smallnest/rpcx-server-demo-nacos:v0.1.0
        ports:
        - containerPort: 8972
        env:
        - name: Nacos_Host
          value: "console.nacos.io"
        - name: Nacos_Port
          value: "80"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP