apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcx-client-demo-nacos-deployment
spec:
  selector:
    matchLabels:
      app: rpcx-client-demo-nacos
  replicas: 1
  template:
    metadata:
      labels:
        app: rpcx-client-demo-nacos
    spec:
      containers:
      - name: rpcx-client-demo-nacos
        image: smallnest/rpcx-client-demo-nacos:v0.1.0
        env:
        - name: Nacos_Host
          value: "console.nacos.io"
        - name: Nacos_Port
          value: "80"